### ISSUE TITLE
提示No such file or directory

### ISSUE THREAD

**Issue by shiyongzhi0117** [medcl/elasticsearch-proxy#10]
编译的时提示的
building proxy 0.2.0_SNAPSHOT
framework does not exist
Cloning into 'framework'...
remote: Enumerating objects: 8626, done.
remote: Total 8626 (delta 0), reused 0 (delta 0), pack-reused 8626
Receiving objects: 100% (8626/8626), 43.77 MiB | 6.58 MiB/s, done.
Resolving deltas: 100% (2223/2223), done.
framework vendor does not exist
Cloning into 'vendor'...
remote: Enumerating objects: 7499, done.
remote: Total 7499 (delta 0), reused 0 (delta 0), pack-reused 7499
Receiving objects: 100% (7499/7499), 101.98 MiB | 9.50 MiB/s, done.
Resolving deltas: 100% (1754/1754), done.
/bin/bash: line 0: cd: /root/elasticsearch-proxy-master/../../infinitbyte/framework/: No such file or directory
make: *** [init] Error 1

**Comment by colegatron** [comment]
Same problem here. Not used to go and its dependencies, but seems it downloads the infinitbyte framework to the wrong folder.
I have tried updating the Makefile with:

>$ git diff Makefile
diff --git a/Makefile b/Makefile
index ba4962f..30631e4 100644
--- a/Makefile
+++ b/Makefile
@@ -38,7 +38,7 @@ MAC       := "Darwin"
 GO_FILES=$(find . -iname '*.go' | grep -v /vendor/)
 PKGS=$(go list ./... | grep -v /vendor/) 
-FRAMEWORK_FOLDER := $(CURDIR)/../../infinitbyte/framework/
+FRAMEWORK_FOLDER := $(CURDIR)/../framework/
 FRAMEWORK_BRANCH := master
 FRAMEWORK_VENDOR_FOLDER := $(CURDIR)/vendor/
 FRAMEWORK_VENDOR_BRANCH := master

But then it fails building with:

>$ make
building proxy 0.2.0_SNAPSHOT
framework vendor does not exist
Clonando en 'vendor'...
remote: Enumerating objects: 7499, done.
remote: Total 7499 (delta 0), reused 0 (delta 0), pack-reused 7499
Recibiendo objetos: 100% (7499/7499), 101.98 MiB | 3.81 MiB/s, listo.
Resolviendo deltas: 100% (1754/1754), listo.
Desde https://github.com/infinitbyte/framework
> * branch            master     -> FETCH_HEAD
Ya está actualizado.
Desde https://github.com/infinitbyte/framework-vendor
> * branch            master     -> FETCH_HEAD
Ya está actualizado.
generate static files
generate main UI pages
generate plugin UI pages
update generated info
update configs
~project_root/k8s/infra/elasticproxy/elasticsearch-proxy-src:~project_root/k8s/infra/elasticproxy/elasticsearch-proxy-src/vendor:~/go
GOPATH=~project_root/k8s/infra/elasticproxy/elasticsearch-proxy-src:~project_root/k8s/infra/elasticproxy/elasticsearch-proxy-src/vendor:~/go CGO_ENABLED=1  GO15VENDOREXPERIMENT="1" go build -ldflags -s -gcflags "-m -m" -o bin/proxy
main.go:26:2: cannot find package "github.com/medcl/elasticsearch-proxy/config" in any of:
	/usr/lib/go-1.10/src/github.com/medcl/elasticsearch-proxy/config (from $GOROOT)
	~project_root/k8s/infra/elasticproxy/elasticsearch-proxy-src/src/github.com/medcl/elasticsearch-proxy/config (from $GOPATH)
	~project_root/k8s/infra/elasticproxy/elasticsearch-proxy-src/vendor/src/github.com/medcl/elasticsearch-proxy/config
	/home/ivan/go/src/github.com/medcl/elasticsearch-proxy/config
main.go:27:2: cannot find package "github.com/medcl/elasticsearch-proxy/model" in any of:
	/usr/lib/go-1.10/src/github.com/medcl/elasticsearch-proxy/model (from $GOROOT)
	~project_root/k8s/infra/elasticproxy/elasticsearch-proxy-src/src/github.com/medcl/elasticsearch-proxy/model (from $GOPATH)
	~project_root/k8s/infra/elasticproxy/elasticsearch-proxy-src/vendor/src/github.com/medcl/elasticsearch-proxy/model
	/home/ivan/go/src/github.com/medcl/elasticsearch-proxy/model
main.go:28:2: cannot find package "github.com/medcl/elasticsearch-proxy/plugin" in any of:
	/usr/lib/go-1.10/src/github.com/medcl/elasticsearch-proxy/plugin (from $GOROOT)
	~project_root/k8s/infra/elasticproxy/elasticsearch-proxy-src/src/github.com/medcl/elasticsearch-proxy/plugin (from $GOPATH)
	~project_root/k8s/infra/elasticproxy/elasticsearch-proxy-src/vendor/src/github.com/medcl/elasticsearch-proxy/plugin
	/home/ivan/go/src/github.com/medcl/elasticsearch-proxy/plugin
Makefile:56: recipe for target 'build' failed
make: *** [build] Error 1
