### ISSUE TITLE
Need your Help : where can i find the package "infini.sh/framework"?

### ISSUE THREAD

**Issue by bestlove4ling** [medcl/elasticsearch-proxy#15]
Need your Help : where can i find the package "infini.sh/framework"?

**Comment by medcl** [comment]
Hi, @bestlove4ling , you can just run `make build`, it will download framework for you.

**Comment by medcl** [comment]
`https://github.com/medcl/infini-framework`
closing now, fell free to reopen.

**Comment by bestlove4ling** [comment]
thx，problem solved
