### ISSUE TITLE
No store any values in redis

### ISSUE THREAD

**Issue by fernandomacho** [medcl/elasticsearch-proxy#16]
Hi the wrapper works file but not store anything in redis.
If config cache as true an run in debug mode, log show :

[09-26 12:39:52] [DBG] [index_handler.go:206] update cache key: proxy_-54974a88788e29ef81f7fe28106cd9e5

This message is write when cache is active, but is show redis this key not exist ....
I don't use go, but think that the init.go set and get return nil ?????

is correct?

**Comment by medcl** [comment]
Hey, @fernandomacho the recent commit removed that to pass build, you may check old commit or download build version, the brand new elasticsearch-gateway in on the way, stay tuned.
