### ISSUE TITLE
Generate bin/proxy error 

### ISSUE THREAD

**Issue by Roarain** [medcl/elasticsearch-proxy#2]
Hello, I was new to golang.

CentOS Linux release 7.4.1708 (Core)
go version go1.9.4 linux/amd64

When run make in "elasticsearch-proxy" directory get this error 
`[root@i-ytu38syv elasticsearch-proxy]# make

building PROXY 0.1.0_SNAPSHOT
generate static files
generate UI pages
update generated info
update configs

/data/elk/elasticsearch-proxy:/data/elk/elasticsearch-proxy/vendor:/root/go
GOPATH=/data/elk/elasticsearch-proxy:/data/elk/elasticsearch-proxy/vendor:/root/go CGO_ENABLED=1  GO15VENDOREXPERIMENT="1" go build -ldflags -s -o bin/proxy
main.go:23:2: cannot find package "github.com/infinitbyte/framework/core/persist" in any of:
	/usr/lib/golang/src/github.com/infinitbyte/framework/core/persist (from $GOROOT)
	/data/elk/elasticsearch-proxy/src/github.com/infinitbyte/framework/core/persist (from $GOPATH)
	/data/elk/elasticsearch-proxy/vendor/src/github.com/infinitbyte/framework/core/persist
	/root/go/src/github.com/infinitbyte/framework/core/persist
main.go:27:2: cannot find package "github.com/infinitbyte/framework/modules/persist" in any of:
	/usr/lib/golang/src/github.com/infinitbyte/framework/modules/persist (from $GOROOT)
	/data/elk/elasticsearch-proxy/src/github.com/infinitbyte/framework/modules/persist (from $GOPATH)
	/data/elk/elasticsearch-proxy/vendor/src/github.com/infinitbyte/framework/modules/persist
	/root/go/src/github.com/infinitbyte/framework/modules/persist
main.go:31:2: cannot find package "github.com/infinitbyte/framework/modules/storage" in any of:
	/usr/lib/golang/src/github.com/infinitbyte/framework/modules/storage (from $GOROOT)
	/data/elk/elasticsearch-proxy/src/github.com/infinitbyte/framework/modules/storage (from $GOPATH)
	/data/elk/elasticsearch-proxy/vendor/src/github.com/infinitbyte/framework/modules/storage
	/root/go/src/github.com/infinitbyte/framework/modules/storage
make: *** [build] Error 1`
When I saw https://github.com/infinitbyte/framework/tree/master/modules, there has no entry listed above.

**Comment by caidongqing** [comment]
The infinitbyte/framework has updated , but the proxy not ,so it occurs the error as you see. you can use the olde version somebody forks

**Comment by mtourne** [comment]
I've found that this particular commit of the "framework" used works : 58b6cc7e5077861f655f10e0653fae5b41ab50ff

**Comment by BigdataEdison** [comment]
@Roarain 
building proxy 0.2.0_SNAPSHOT
From https://github.com/infinitbyte/framework
 * branch            master     -> FETCH_HEAD
Already up to date.
From https://github.com/infinitbyte/framework-vendor
 * branch            master     -> FETCH_HEAD
Already up to date.
generate static files
generate main UI pages
generate plugin UI pages
update generated info
update configs
/Users/blueskysky/esproxy/elasticsearch-proxy:/Users/blueskysky/esproxy/elasticsearch-proxy/vendor:~/go
GOPATH=/Users/blueskysky/esproxy/elasticsearch-proxy:/Users/blueskysky/esproxy/elasticsearch-proxy/vendor:~/go CGO_ENABLED=1  GO15VENDOREXPERIMENT="1" go build -ldflags -s -gcflags "-m -m" -o bin/proxy
../../go/src/github.com/medcl/elasticsearch-proxy/vendor/src/github.com/go-redis/redis/cluster.go:16:2: use of internal package github.com/go-redis/redis/internal not allowed
../../go/src/github.com/medcl/elasticsearch-proxy/vendor/src/github.com/go-redis/redis/ring.go:14:2: use of internal package github.com/go-redis/redis/internal/consistenthash not allowed
../../go/src/github.com/medcl/elasticsearch-proxy/vendor/src/github.com/go-redis/redis/cluster.go:17:2: use of internal package github.com/go-redis/redis/internal/hashtag not allowed
../../go/src/github.com/medcl/elasticsearch-proxy/vendor/src/github.com/go-redis/redis/cluster.go:18:2: use of internal package github.com/go-redis/redis/internal/pool not allowed
../../go/src/github.com/medcl/elasticsearch-proxy/vendor/src/github.com/go-redis/redis/cluster.go:19:2: use of internal package github.com/go-redis/redis/internal/proto not allowed
make: *** [build] Error 1

**Comment by BigdataEdison** [comment]
@Roarain  @caidongqing  pls take a look at this problem ，it's a very difficult problem.

**Comment by meizhennan** [comment]
huangjunjiedeMacBook-Pro:elasticsearch-proxy-master huangjunjie$ make
building proxy 0.2.0_SNAPSHOT
From https://github.com/infinitbyte/framework
 * branch            master     -> FETCH_HEAD
Already up to date.
From https://github.com/infinitbyte/framework-vendor
 * branch            master     -> FETCH_HEAD
Already up to date.
generate static files
generate main UI pages
generate plugin UI pages
update generated info
fatal: your current branch 'master' does not have any commits yet
update configs
/Users/huangjunjie/IdeaProjects/GoProjects/src/elasticsearch-proxy-master:/Users/huangjunjie/IdeaProjects/GoProjects/src/elasticsearch-proxy-master/vendor:~/go
GOPATH=/Users/huangjunjie/IdeaProjects/GoProjects/src/elasticsearch-proxy-master:/Users/huangjunjie/IdeaProjects/GoProjects/src/elasticsearch-proxy-master/vendor:~/go CGO_ENABLED=1  GO15VENDOREXPERIMENT="1" go build -ldflags -s -gcflags "-m -m" -o bin/proxy
# _/Users/huangjunjie/IdeaProjects/GoProjects/src/elasticsearch-proxy-master
./main.go:31:6: cannot inline main: unhandled op DEFER
./main.go:42:18: inlining call to util.TrimSpaces func(string) string { return strings.TrimSpace(util.str) }
./main.go:42:51: inlining call to util.TrimSpaces func(string) string { return strings.TrimSpace(util.str) }
./main.go:42:90: inlining call to util.TrimSpaces func(string) string { return strings.TrimSpace(util.str) }
./main.go:41:25: inlining call to framework.NewApp func(string, string, string, string, string, string, string) *framework.App { return &framework.App literal }
./main.go:48:12: cannot inline main.func1: function too complex: cost 129 exceeds budget 80
./main.go:53:28: inlining call to module.RegisterUserPlugin func(module.Module) { module.m.user = append(module.m.user, module.mod) }
./main.go:58:5: can inline main.func2 as: func() { orm.RegisterSchema(&model.Request literal) }
./main.go:41:25: &framework.App literal escapes to heap
./main.go:48:12: main func literal does not escape
./main.go:58:5: main func literal does not escape
./main.go:53:47: plugin.ProxyPlugin literal escapes to heap
./main.go:59:22: &model.Request literal escapes to heap
./main.go:59:22: &model.Request literal escapes to heap
restore generated info
