### ISSUE TITLE
请问项目还会继续更新吗

### ISSUE THREAD

**Issue by caidongqing** [medcl/elasticsearch-proxy#3]
我看到 elasticsearch-proxy 的依赖程序 framework正在更新，不知道这个是否还继续更新。

**Comment by ljw7630** [comment]
> 我看到 elasticsearch-proxy 的依赖程序 framework正在更新，不知道这个是否还继续更新。

如果你只需要一个分发proxy的话,  可以参考我这个 https://github.com/ljw7630/multicast-http-proxy  只需要150行代码, 做了一个http的分发. 功能性跟这个没法比, 胜在简单
