### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by BigdataEdison** [medcl/elasticsearch-proxy#7]
I am very sorry  I had encountered  a problem , Could you pls provide some support, 
当进入到elasticsearch-proxy内，执行make后，报了如下error： @medcl 
building proxy 0.2.0_SNAPSHOT
From https://github.com/infinitbyte/framework
 * branch            master     -> FETCH_HEAD
Already up to date.
From https://github.com/infinitbyte/framework-vendor
 * branch            master     -> FETCH_HEAD
Already up to date.
generate static files
generate main UI pages
generate plugin UI pages
update generated info
update configs
/Users/blueskysky/elasticsearch-proxy:/Users/blueskysky/elasticsearch-proxy/vendor:~/go
GOPATH=/Users/blueskysky/elasticsearch-proxy:/Users/blueskysky/elasticsearch-proxy/vendor:~/go CGO_ENABLED=1  GO15VENDOREXPERIMENT="1" go build -ldflags -s -gcflags "-m -m" -o bin/proxy
main.go:26:2: cannot find package "github.com/medcl/elasticsearch-proxy/config" in any of:
	/usr/local/go/src/github.com/medcl/elasticsearch-proxy/config (from $GOROOT)
	/Users/blueskysky/elasticsearch-proxy/src/github.com/medcl/elasticsearch-proxy/config (from $GOPATH)
	/Users/blueskysky/elasticsearch-proxy/vendor/src/github.com/medcl/elasticsearch-proxy/config
	/Users/blueskysky/go/src/github.com/medcl/elasticsearch-proxy/config
main.go:27:2: cannot find package "github.com/medcl/elasticsearch-proxy/model" in any of:
	/usr/local/go/src/github.com/medcl/elasticsearch-proxy/model (from $GOROOT)
	/Users/blueskysky/elasticsearch-proxy/src/github.com/medcl/elasticsearch-proxy/model (from $GOPATH)
	/Users/blueskysky/elasticsearch-proxy/vendor/src/github.com/medcl/elasticsearch-proxy/model
	/Users/blueskysky/go/src/github.com/medcl/elasticsearch-proxy/model
main.go:28:2: cannot find package "github.com/medcl/elasticsearch-proxy/plugin" in any of:
	/usr/local/go/src/github.com/medcl/elasticsearch-proxy/plugin (from $GOROOT)
	/Users/blueskysky/elasticsearch-proxy/src/github.com/medcl/elasticsearch-proxy/plugin (from $GOPATH)
	/Users/blueskysky/elasticsearch-proxy/vendor/src/github.com/medcl/elasticsearch-proxy/plugin
	/Users/blueskysky/go/src/github.com/medcl/elasticsearch-proxy/plugin
make: *** [build] Error 1

**Comment by medcl** [comment]
```
mkdir ~/go/src/github.com/medcl/ -p
cd ~/go/src/github.com/medcl/
git clone https://github.com/medcl/elasticsearch-proxy.git
cd elasticsearch-proxy
make
```

**Comment by BigdataEdison** [comment]
@medcl  medcl , Could you pls take a look at it,about main.go :  
building proxy 0.2.0_SNAPSHOT
From https://github.com/infinitbyte/framework
 * branch            master     -> FETCH_HEAD
Already up to date.
From https://github.com/infinitbyte/framework-vendor
 * branch            master     -> FETCH_HEAD
Already up to date.
generate static files
generate main UI pages
generate plugin UI pages
update generated info
update configs
/Users/blueskysky/go/src/github.com/medcl/elasticsearch-proxy:/Users/blueskysky/go/src/github.com/medcl/elasticsearch-proxy/vendor:~/go
GOPATH=/Users/blueskysky/go/src/github.com/medcl/elasticsearch-proxy:/Users/blueskysky/go/src/github.com/medcl/elasticsearch-proxy/vendor:~/go CGO_ENABLED=1  GO15VENDOREXPERIMENT="1" go build -ldflags -s -gcflags "-m -m" -o bin/proxy
# github.com/medcl/elasticsearch-proxy
./main.go:31:6: cannot inline main: unhandled op DEFER
./main.go:42:18: inlining call to util.TrimSpaces func(string) string { return strings.TrimSpace(util.str) }
./main.go:42:18: inlining call to strings.TrimSpace func(string) string { return strings.TrimFunc(strings.s, unicode.IsSpace) }
./main.go:42:51: inlining call to util.TrimSpaces func(string) string { return strings.TrimSpace(util.str) }
./main.go:42:51: inlining call to strings.TrimSpace func(string) string { return strings.TrimFunc(strings.s, unicode.IsSpace) }
./main.go:42:90: inlining call to util.TrimSpaces func(string) string { return strings.TrimSpace(util.str) }
./main.go:42:90: inlining call to strings.TrimSpace func(string) string { return strings.TrimFunc(strings.s, unicode.IsSpace) }
./main.go:41:25: inlining call to framework.NewApp func(string, string, string, string, string, string, string) *framework.App { return &framework.App literal }
./main.go:48:12: cannot inline main.func1: function too complex: cost 129 exceeds budget 80
./main.go:53:28: inlining call to module.RegisterUserPlugin func(module.Module) { module.m.user = append(module.m.user, module.mod) }
./main.go:58:5: can inline main.func2 as: func() { orm.RegisterSchema(&model.Request literal) }
./main.go:41:25: &framework.App literal escapes to heap
./main.go:41:25: 	from ~R0 (assign-pair) at ./main.go:41:25
./main.go:41:25: 	from app (assigned) at ./main.go:41:6
./main.go:41:25: 	from app (passed to call[argument escapes]) at ./main.go:44:10
./main.go:53:47: plugin.ProxyPlugin literal escapes to heap
./main.go:53:47: 	from module.mod (assign-pair) at ./main.go:53:28
./main.go:53:47: 	from append(module.m.user, module.mod) (appended to slice) at ./main.go:53:28
./main.go:59:22: &model.Request literal escapes to heap
./main.go:59:22: 	from &model.Request literal (passed to call[argument escapes]) at ./main.go:59:21
./main.go:59:22: &model.Request literal escapes to heap
./main.go:59:22: 	from &model.Request literal (interface-converted) at ./main.go:59:22
./main.go:59:22: 	from &model.Request literal (passed to call[argument escapes]) at ./main.go:59:21
./main.go:48:12: main func literal does not escape
./main.go:58:5: main func literal does not escape
restore generated info

**Comment by medcl** [comment]
上面的编译警告可以忽略。

**Comment by BigdataEdison** [comment]
@medcl  ok ,get it

**Comment by BigdataEdison** [comment]
0.2.0_SNAPSHOT,  87248ab, Thu Jul 25 22:49:17 2019 +0800, medcl, update config and readme
[08-01 21:58:57] [INF] [instance.go:23] workspace: data/proxy/nodes/0
[08-01 21:58:57] [INF] [api.go:154] auto generate server cert
[08-01 21:58:58] [INF] [api.go:243] api server listen at: 0.0.0.0:2900
[08-01 21:58:58] [ERR] [init.go:67] cache server is not ready: dial tcp [::1]:6379: connect: connection refused
[08-01 21:58:58] [ERR] [app.go:241] shutdown: dial tcp [::1]:6379: connect: connection refused

**Comment by medcl** [comment]
配置文件的 cache 设置 enabled:false
